legacy: false
repo_root_dir: "/home/jinxu/code/Ego4d_mmpose/Ego4d"
data_dir: "/media/jinxu/New\ Volume/ego4dData"
cache_root_dir: "/media/jinxu/New\ Volume/ego4dData"
gpu_id: 0
mode: "preprocess"
inputs:
  from_frame_number: 18060
  to_frame_number: 18210
  take_name: "sfu_cooking_007_3"
  take_uid: null
  metadata_json_path: null
  aria_trajectory_path: null
  exo_trajectory_path: null
  aria_streams:
    - rgb
    - slam-left
    - slam-right
  exo_timesync_name_to_calib_name: null
mode_preprocess:
  dataset_name: "dataset"
  vrs_bin_path: "vrs"
  download_video_files: true
  force_download: false
  extract_all_aria_frames: false
mode_bbox:
  detector_config: "ego4d/internal/human_pose/external/mmlab/mmpose/demo/mmdetection_cfg/faster_rcnn_r50_fpn_coco.py"
  detector_checkpoint: 'https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth'
  use_aria_trajectory: true
  human_height: 1.5
  human_radius: 0.3
  min_bbox_score: 0.7
  min_area_ratio: 0.005
mode_pose2d:
  pose_config: "ego4d/internal/human_pose/external/mmlab/mmpose/configs/wholebody_2d_keypoint/topdown_heatmap/coco-wholebody/td-hm_hrnet-w48_dark-8xb32-210e_coco-wholebody-384x288.py"
  pose_checkpoint: "https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_coco_wholebody_384x288_dark-f5726563_20200918.pth"
  dummy_pose_config: 'ego4d/internal/human_pose/external/mmlab/mmpose/configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_hrnet-w48_8xb32-210e_coco-256x192.py'
  dummy_pose_checkpoint: 'https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_coco_256x192-b9e0b3ab_20200708.pth'
  hand_pose_config: 'ego4d/internal/human_pose/external/mmlab/mmpose/projects/rtmpose/rtmpose/hand_2d_keypoint/rtmpose-m_8xb32-210e_coco-wholebody-hand-256x256.py'
  hand_pose_ckpt: 'https://download.openmmlab.com/mmpose/v1/projects/rtmposev1/rtmpose-m_simcc-hand5_pt-aic-coco_210e-256x256-74fb594_20230320.pth'
mode_pose3d:
  start_frame: 0
  end_frame: -1
